"""The strict-parser contract, shared with the Rust reference implementation.

fixtures/jcs_vectors.json is the second half of the canonicalisation contract.
fixtures/canon_vectors.json pins the VALUE MODEL — carriers, bytes, digests —
with Python as the measured original and a Rust test matching it. This file
pins the BOUNDARY: 75 deliberately messy renderings that must canonicalise to
byte-identical output, and 13 inputs that must be refused with the same named
class in both languages. Direction of truth is the mirror image: the vectors
were generated by the Rust module (core/ledger/src/jcs.rs), which carries RFC
8785's own sample string and a 10,000-case property test; parse_strict must
reproduce its bytes and its refusals exactly.

Why the boundary needs its own contract: json.loads keeps the last duplicate
key silently, admits lone-surrogate escapes, and parses fractions. Any of the
three at a trust boundary signs a document with a reading the operator never
saw. A refusal class that drifts between languages is a place where one side
signs what the other rejects — which is the definition of a forgery window.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from sentinelwipe.canon import CanonError, canonicalize, parse_strict

_REPO = Path(__file__).resolve().parents[1]
_DOC_BYTES = (_REPO / "fixtures" / "jcs_vectors.json").read_bytes()
_DOC = json.loads(_DOC_BYTES)

VECTORS = _DOC["vectors"]
REFUSALS = _DOC["refusals"]


def test_the_committed_file_is_a_fixed_point_of_this_implementation():
    """The vector file is itself canonical JCS. If parse_strict + canonicalize
    cannot reproduce its exact bytes, one of them disagrees with the reference
    before a single vector has run."""
    assert canonicalize(parse_strict(_DOC_BYTES)) == _DOC_BYTES


def test_the_table_is_present_and_not_vacuous():
    counts = _DOC["counts"]
    assert counts["vectors"] == len(VECTORS) >= 70, "vector table truncated"
    assert counts["refusals"] == len(REFUSALS) >= 12, "refusal table truncated"
    names = [v["name"] for v in VECTORS]
    # The two vectors that exist because orderings disagree must be present.
    assert "astral-key-sorts-before-u+e000" in names
    assert "rfc-8785-sample-string" in names


@pytest.mark.parametrize("vec", VECTORS, ids=lambda v: v["name"])
def test_messy_input_canonicalises_to_the_reference_bytes(vec):
    got = canonicalize(parse_strict(vec["input"].encode("utf-8")))
    assert got == vec["canonical"].encode("utf-8"), (
        f"{vec['name']}: python bytes differ from the Rust reference"
    )


@pytest.mark.parametrize("ref", REFUSALS, ids=lambda r: r["name"])
def test_refusals_carry_the_same_class_in_both_languages(ref):
    with pytest.raises(CanonError) as ei:
        parse_strict(ref["input"].encode("utf-8"))
    assert ei.value.kind == ref["error"], (
        f"{ref['name']}: python refused as {ei.value.kind!r}, "
        f"the reference says {ref['error']!r}"
    )


def test_sorting_agreement_is_not_an_accident_of_ascii():
    """Direct probes of the orderings Python's defaults would get wrong.

    sorted() on str compares code points, so U+10000 lands after U+E000;
    UTF-16 code units put it first. The empty key sorts before everything
    under any rule. Keys are built with chr() because a raw U+E000 in source
    is INVISIBLE: the first version of this test carried one, pasted inside
    what read as an empty string, and so asserted a different - accidentally
    true - property while looking like this one. ASCII-only source is the
    fix, not sharper eyes."""
    astral, e000, empty = chr(0x10000), chr(0xE000), ""
    got = canonicalize({e000: 1, astral: 2, empty: 3})
    expected = (
        "{" + '"' + empty + '":3,'
        + '"' + astral + '":2,'
        + '"' + e000 + '":1}'
    ).encode("utf-8")
    assert got == expected
    # Under code-point ordering the astral key would land AFTER U+E000;
    # byte positions in the canonical output prove it lands before.
    two = canonicalize({astral: 1, e000: 2})
    assert two.index(astral.encode("utf-8")) < two.index(e000.encode("utf-8"))